### ISSUE TITLE
Upcoming changes around `-Zembed-bitcode`

### ISSUE THREAD

**Issue by alexcrichton** [getditto/rust-bitcode#9]
Hello! I found this through an article today, and wanted to give y'all a heads up at some possible changes which may make things easier for y'all here.

https://github.com/rust-lang/rust/pull/71528 is an effort to move all of rustc's storage of LLVM bitcode into object files by default instead of having some extra `*.bc.z` files in rlibs. Once that lands we'll be stabilizing `-Cembed-bitcode` as well so you won't have to use a `-Z` flag. 

Some other notes that I saw while reading some scripts here:

* If y'all are up for it the [patch you have](https://github.com/getditto/rust-bitcode/blob/master/patches/rust_embed_cmdline.diff) would likely be welcome upstream. We'd probably need to add a new target spec field so it's ios-specific, but that wouldn't be too too hard!
* If you'd like I'd be happen to [turn `-fembed-bitcode` on by default in `cc`](https://github.com/getditto/rust-bitcode/blob/5633a928fed1a1782a58b45bc88193948bc9069d/build.sh#L47) so you don't have to specify an extra env var
* I think it'd be fine to embed bitcode by default on all the ios targets (I believe there's an existing custom target spec option for this), which would remove the need for this [extra configuration](https://github.com/getditto/rust-bitcode/blob/5633a928fed1a1782a58b45bc88193948bc9069d/build.sh#L46).

**Comment by thombles** [comment]
Hi, thanks for the welcome news! It will be great not to require `-Z`.

I'd thought about upstreaming that patch but I wasn't sure whether it would be desirable or where it would fit in, but you've just answered both those questions for me! I'll look into it.

I agree embedding bitcode is a sensible default for any iOS target, in `cc` or otherwise. I haven't spotted an obvious setting in the target spec fields but I might not be looking in the right place.

**Comment by alexcrichton** [comment]
Oh I thought that this was actually already implemented but it appears I was wrong! I think what you'll want to do is:

* Add some new fields to [this structure](https://github.com/rust-lang/rust/blob/2454a68cfbb63aa7b8e09fe05114d5f98b2f9740/src/librustc_target/spec/mod.rs#L628-L881)
  * one would be "target forces embed bitcode"
  * another would be "default value of `.llvmcmd`"
* The value of llvmcmd is threaded through to [this location](https://github.com/rust-lang/rust/blob/2454a68cfbb63aa7b8e09fe05114d5f98b2f9740/src/librustc_codegen_llvm/back/write.rs#L810)
* Embedding bitcode is threaded through [to here](https://github.com/rust-lang/rust/blob/2454a68cfbb63aa7b8e09fe05114d5f98b2f9740/src/librustc_codegen_ssa/back/write.rs#L375-L379) where it reads the value from the target spec. (if it's forced then the CLI value would be ignored most likely)
* You'd then update these target spec values for the ios targets that need it.

**Comment by thombles** [comment]
Building on the work mentioned in OP, the cmdline patch is now upstreamed along with a tweak that means aarch64-apple-ios will always embed bitcode without needing to use any `-Z` or `-C` flags: https://github.com/rust-lang/rust/pull/71970

Presumably these improvements will land in 1.44.0, after which this repo will have less work to do and we can simplify things a bit. 🎉

For Ditto's purposes we'll most likely drop back to the stable channel. If there's anyone relying on the binaries who wants the nightly channel we could keep publishing those also.
